export const SOURCE_TYPE_INPUT_SENSORY_NEURON = 0
export const SOURCE_TYPE_INPUT_INTERNAL_NEURON = 1
export const SINK_TYPE_INTERNAL_NEURON = 0
export const SINK_TYPE_OUTPUT_ACTION_NEURON = 1
export const WEIGHT_FLOATING_POINT = 8192
export const NUM_SENSORY_NEURONS = 8
export const NUM_ACTION_OUTPUT_NEURONS = 3
